name: AndroidBuild

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '18'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run Unit test
        run: ./gradlew test

  build:
    name: Generate APK
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '18'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Assemble App APK
        run: ./gradlew assembleDebug
      - name: Upload App APK
        uses: actions/upload-artifact@v4.0.0
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
      - name: Assemble Android Instrumented Unit Test
        run: ./gradlew assembleDebugAndroidTest
      - name: Upload Android Test APK
        uses: actions/upload-artifact@v4.0.0
        with:
          name: app-debug-androidTest
          path: app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk

  firebase-test:
    name: Run UI tests with Firebase Test Lab
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Download app APK
        uses: actions/download-artifact@v4
        with:
          name: app-debug
      - name: Download Android test APK
        uses: actions/download-artifact@v4
        with:
          name: app-debug-androidTest
      - name: Run tests on Firebase Test Lab
        uses: asadmansr/Firebase-Test-Lab-Action@v1.0
        with:
          arg-spec: '.github/data/tests.yml:android-pixel-4'
        env:
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}

  release:
    name: Release Project
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Download app APK
        uses: actions/download-artifact@v4
        with:
          name: app-debug
      - name: Create new release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          files: app-debug/app-debug.apk
          tag_name: ${{ github.run_number }}
          name: Release ${{ github.run_number }}